const damage = [
    {
        id: "damage001",
        fluid: "C1-C2",
        data: {
            CAINLGA: 8.669,
            CAINLGB: 0.98,
            CAINLLA: null,
            CAINLLB: null,
            CAILGA: 55.13,
            CAILGB: 0.95,
            CAILLA: null,
            CAILLB: null,
            IAINLGA: 6.469,
            IAINLGB: 0.67,
            IAINLLA: null,
            IAINLLB: null,
            IAILGA: 163.7,
            IAILGB: 0.62,
            IAILLA: null,
            IAILLB: null,
        }
    },
    {
        id: "damage002",
        fluid: "C3-C4",
        data: {
            CAINLGA: 10.13,
            CAINLGB: 1,
            CAINLLA: null,
            CAINLLB: null,
            CAILGA: 64.23,
            CAILGB: 1,
            CAILLA: null,
            CAILLB: null,
            IAINLGA: 4.59,
            IAINLGB: 0.72,
            IAINLLA: null,
            IAINLLB: null,
            IAILGA: 79.94,
            IAILGB: 0.62,
            IAILLA: null,
            IAILLB: null,
        }
    },
    {
        id: "damage003",
        fluid: "C5",
        data: {
            CAINLGA: 5.115,
            CAINLGB: 0.99,
            CAINLLA: 100.6,
            CAINLLB: 0.89,
            CAILGA: 62.41,
            CAILGB: 1,
            CAILLA: null,
            CAILLB: null,
            IAINLGA: 2.214,
            IAINLGB: 0.73,
            IAINLLA: null,
            IAINLLB: null,
            IAILGA: 41.38,
            IAILGB: 0.61,
            IAILLA: null,
            IAILLB: null,
        }
    },
    {
        id: "damage004",
        fluid: "C6-C8",
        data: {
            CAINLGA: 5.849,
            CAINLGB: 0.98,
            CAINLLA: 34.17,
            CAINLLB: 0.89,
            CAILGA: 63.98,
            CAILGB: 1,
            CAILLA: 103.4,
            CAILLB: 0.95,
            IAINLGA: 2.188,
            IAINLGB: 0.66,
            IAINLLA: 0.794,
            IAINLLB: 0.78,
            IAILGA: 41.49,
            IAILGB: 0.61,
            IAILLA: 8.18,
            IAILLB: 0.55,
        }
    },
    {
        id: "damage005",
        fluid: "C9-C12",
        data: {
            CAINLGA: 2.419,
            CAINLGB: 0.98,
            CAINLLA: 24.6,
            CAINLLB: 90,
            CAILGA: 76.98,
            CAILGB: 0.95,
            CAILLA: 110.3,
            CAILLB: 0.95,
            IAINLGA: 1.111,
            IAINLGB: 0.66,
            IAINLLA: 0.559,
            IAINLLB: 0.76,
            IAILGA: 42.28,
            IAILGB: 0.61,
            IAILLA: 0.848,
            IAILLB: 0.53,
        }
    }, 
    {
        id: "damage006",
        fluid: "C13-C16",
        data: {
            CAINLGA: null,
            CAINLGB: null,
            CAINLLA: 12.11,
            CAINLLB: 0.9,
            CAILGA: null,
            CAILGB: null,
            CAILLA: 196.7,
            CAILLB: 0.92,
            IAINLGA: null,
            IAINLGB: null,
            IAINLLA: 0.086,
            IAINLLB: 0.88,
            IAILGA: null,
            IAILGB: null,
            IAILLA: 1.714,
            IAILLB: 0.88,
        }
    },
    {
        id: "damage007",
        fluid: "C17-C25",
        data: {
            CAINLGA: null,
            CAINLGB: null,
            CAINLLA: 3.785,
            CAINLLB: 0.9,
            CAILGA: null,
            CAILGB: null,
            CAILLA: 165.5,
            CAILLB: 0.92,
            IAINLGA: null,
            IAINLGB: null,
            IAINLLA: 0.021,
            IAINLLB: 0.006,
            IAILGA: null,
            IAILGB: null,
            IAILLA: 1.068,
            IAILLB: 0.91,
        }
    },
    {
        id: "damage008",
        fluid: "C25+",
        data: {
            CAINLGA: null,
            CAINLGB: null,
            CAINLLA: 2.098,
            CAINLLB: 0.91,
            CAILGA: null,
            CAILGB: null,
            CAILLA: 103,
            CAILLB: 0.9,
            IAINLGA: null,
            IAINLGB: null,
            IAINLLA: 0.006,
            IAINLLB: 0.99,
            IAILGA: null,
            IAILGB: null,
            IAILLA: 0.284,
            IAILLB: 0.99,
        }
    },
    {
        id: "damage009",
        fluid: "H2",
        data: {
            CAINLGA: 13.13,
            CAINLGB: 0.992,
            CAINLLA: null,
            CAINLLB: null,
            CAILGA: 86.02,
            CAILGB: 1,
            CAILLA: null,
            CAILLB: null,
            IAINLGA: 9.605,
            IAINLGB: 0.657,
            IAINLLA: null,
            IAINLLB: null,
            IAILGA: 216.5,
            IAILGB: 0.618,
            IAILLA: null,
            IAILLB: null,
        }
    },
    {
        id: "damage010",
        fluid: "H2S",
        data: {
            CAINLGA: 6.554,
            CAINLGB: 1,
            CAINLLA: null,
            CAINLLB: null,
            CAILGA: 38.11,
            CAILGB: 0.89,
            CAILLA: null,
            CAILLB: null,
            IAINLGA: 22.63,
            IAINLGB: 0.63,
            IAINLLA: null,
            IAINLLB: null,
            IAILGA: 53.72,
            IAILGB: 0.61,
            IAILLA: null,
            IAILLB: null,
        }
    },
    {
        id: "damage011",
        fluid: "HF",
        data: {
            CAINLGA: null,
            CAINLGB: null,
            CAINLLA: null,
            CAINLLB: null,
            CAILGA: null,
            CAILGB: null,
            CAILLA: null,
            CAILLB: null,
            IAINLGA: null,
            IAINLGB: null,
            IAINLLA: null,
            IAINLLB: null,
            IAILGA: null,
            IAILGB: null,
            IAILLA: null,
            IAILLB: null,
        }
    },
    {
        id: "damage012",
        fluid: "Acromatics",
        data: {
            CAINLGA: 3.952,
            CAINLGB: 1.097,
            CAINLLA: 21.1,
            CAINLLB: 1,
            CAILGA: 80.11,
            CAILGB: 1.055,
            CAILLA: null,
            CAILLB: null,
            IAINLGA: 18.04,
            IAINLGB: 0.667,
            IAINLLA: 14.36,
            IAINLLB: 1,
            IAILGA: 83.68,
            IAILGB: 0.713,
            IAILLA: 143.6,
            IAILLB: 1,
        }
    },
    {
        id: "damage013",
        fluid: "Styrene / Aromatic",
        data: {
            CAINLGA: 3.952,
            CAINLGB: 1.097,
            CAINLLA: 21.1,
            CAINLLB: 1,
            CAILGA: 80.11,
            CAILGB: 1.055,
            CAILLA: null,
            CAILLB: null,
            IAINLGA: 1.804,
            IAINLGB: 0.667,
            IAINLLA: 14.36,
            IAINLLB: 1,
            IAILGA: 83.68,
            IAILGB: 0.713,
            IAILLA: 143.6,
            IAILLB: 1,
        }
    },
    {
        id: "damage014",
        fluid: "CO",
        data: {
            CAINLGA: 0.04,
            CAINLGB: 1.752,
            CAINLLA: null,
            CAINLLB: null,
            CAILGA: null,
            CAILGB: null,
            CAILLA: null,
            CAILLB: null,
            IAINLGA: 10.97,
            IAINLGB: 0.667,
            IAINLLA: null,
            IAINLLB: null,
            IAILGA: null,
            IAILGB: null,
            IAILLA: null,
            IAILLB: null,
        }
    },
    {
        id: "damage015",
        fluid: "DEE",
        data: {
            CAINLGA: 9.072,
            CAINLGB: 1.134,
            CAINLLA: 164.2,
            CAINLLB: 1.106,
            CAILGA: 67.42,
            CAILGB: 1.033,
            CAILLA: 976,
            CAILLB: 0.649,
            IAINLGA: 24.51,
            IAINLGB: 0.667,
            IAINLLA: 0.981,
            IAINLLB: 0.919,
            IAILGA: null,
            IAILGB: null,
            IAILLA: 1.09,
            IAILLB: 0.919,
        }
    },
    {
        id: "damage016",
        fluid: "Methanol",
        data: {
            CAINLGA: 0.005,
            CAINLGB: 0.909,
            CAINLLA: 340.4,
            CAINLLB: 0.934,
            CAILGA: null,
            CAILGB: null,
            CAILLA: null,
            CAILLB: null,
            IAINLGA: 4.425,
            IAINLGB: 0.667,
            IAINLLA: 0.363,
            IAINLLB: 0.9,
            IAILGA: null,
            IAILGB: null,
            IAILLA: null,
            IAILLB: null,
        }
    },
    {
        id: "damage017",
        fluid: "EO",
        data: {
            CAINLGA: 6.712,
            CAINLGB: 1.069,
            CAINLLA: null,
            CAINLLB: null,
            CAILGA: null,
            CAILGB: null,
            CAILLA: null,
            CAILLB: null,
            IAINLGA: 21.46,
            IAINLGB: 0.667,
            IAINLLA: null,
            IAINLLB: null,
            IAILGA: null,
            IAILGB: null,
            IAILLA: null,
            IAILLB: null,
        }
    },
    {
        id: "damage018",
        fluid: "Pyroporic",
        data: {
            CAINLGA: 2.419,
            CAINLGB: 0.98,
            CAINLLA: 24.6,
            CAINLLB: 0.9,
            CAILGA: 76.98,
            CAILGB: 0.95,
            CAILLA: 110.3,
            CAILLB: 0.95,
            IAINLGA: 1.111,
            IAINLGB: 0.66,
            IAINLLA: 0.559,
            IAINLLB: 0.76,
            IAILGA: 42.28,
            IAILGB: 0.61,
            IAILLA: 0.848,
            IAILLB: 0.53,
        }
    }
]

const flamable = [
    {
        id: "damage001",
        fluid: "C1-C2",
        data: {
            CAINLGA: 21.83,
            CAINLGB: 0.96,
            CAINLLA: null,
            CAINLLB: null,
            CAILGA: 143.2,
            CAILGB: 0.92,
            CAILLA: null,
            CAILLB: null,
            IAINLGA: 12.46,
            IAINLGB: 0.67,
            IAINLLA: null,
            IAINLLB: null,
            IAILGA: 473.9,
            IAILGB: 0.63,
            IAILLA: null,
            IAILLB: null,
        }
    },
    {
        id: "damage002",
        fluid: "C3-C4",
        data: {
            CAINLGA: 25.64,
            CAINLGB: 1,
            CAINLLA: null,
            CAINLLB: null,
            CAILGA: 171.4,
            CAILGB: 1,
            CAILLA: null,
            CAILLB: null,
            IAINLGA: 9.702,
            IAINLGB: 0.75,
            IAINLLA: null,
            IAINLLB: null,
            IAILGA: 270.4,
            IAILGB: 0.63,
            IAILLA: null,
            IAILLB: null,
        }
    },
    {
        id: "damage003",
        fluid: "C5",
        data: {
            CAINLGA: 12.71,
            CAINLGB: 1,
            CAINLLA: 290.1,
            CAINLLB: 0.89,
            CAILGA: 166.1,
            CAILGB: 1,
            CAILLA: null,
            CAILLB: null,
            IAINLGA: 4.82,
            IAINLGB: 0.76,
            IAINLLA: 0.79,
            IAINLLB: 0.85,
            IAILGA: 146.7,
            IAILGB: 0.63,
            IAILLA: null,
            IAILLB: null,
        }
    },
    {
        id: "damage004",
        fluid: "C6-C8",
        data: {
            CAINLGA: 13.49,
            CAINLGB: 0.96,
            CAINLLA: 96.88,
            CAINLLB: 0.89,
            CAILGA: 169.7,
            CAILGB: 1,
            CAILLA: 252.8,
            CAILLB: 0.92,
            IAINLGA: 4.216,
            IAINLGB: 0.67,
            IAINLLA: 2.168,
            IAINLLB: 0.78,
            IAILGA: 147.2,
            IAILGB: 0.63,
            IAILLA: 31.89,
            IAILLB: 0.54,
        }
    },
    {
        id: "damage005",
        fluid: "C19-C12",
        data: {
            CAINLGA: 5.755,
            CAINLGB: 0.96,
            CAINLLA: 70.03,
            CAINLLB: 0.89,
            CAILGA: 188.6,
            CAILGB: 0.92,
            CAILLA: 269.4,
            CAILLB: 0.92,
            IAINLGA: 2.035,
            IAINLGB: 0.66,
            IAINLLA: 1.609,
            IAINLLB: 0.76,
            IAILGA: 151 ,
            IAILGB: 0.63,
            IAILLA: 2.847,
            IAILLB: 0.54,
        }
    },
    {
        id: "damage006",
        fluid: "C13-C16",
        data: {
            CAINLGA: null,
            CAINLGB: null,
            CAINLLA: 34.36,
            CAINLLB: 0.89,
            CAILGA: null,
            CAILGB: null,
            CAILLA: 539.4,
            CAILLB: 0.9,
            IAINLGA: null,
            IAINLGB: null,
            IAINLLA: 0.242,
            IAINLLB: 0.88,
            IAILGA: null,
            IAILGB: null,
            IAILLA: 4.843,
            IAILLB: 0.88,
        }
    },
    {
        id: "damage007",
        fluid: "C17-C25",
        data: {
            CAINLGA: null,
            CAINLGB: null,
            CAINLLA: 10.7,
            CAINLLB: 0.89,
            CAILGA: null,
            CAILGB: null,
            CAILLA: 458,
            CAILLB: 0.9,
            IAINLGA: null,
            IAINLGB: null,
            IAINLLA: 0.061,
            IAINLLB: 0.91,
            IAILGA: null,
            IAILGB: null,
            IAILLA: 3.052,
            IAILLB: 0.91,
        }
    },
    {
        id: "damage008",
        fluid: "C25+",
        data: {
            CAINLGA: null,
            CAINLGB: null,
            CAINLLA: 6.196,
            CAINLLB: 0.89,
            CAILGA: null,
            CAILGB: null,
            CAILLA: 303.6,
            CAILLB: 0.9,
            IAINLGA: null,
            IAINLGB: null,
            IAINLLA: 0.016,
            IAINLLB: 0.99,
            IAILGA: null,
            IAILGB: null,
            IAILLA: 0.833,
            IAILLB: 0.99,
        }
    },
    {
        id: "damage009",
        fluid: "H2",
        data: {
            CAINLGA: 32.05,
            CAINLGB: 0.933,
            CAINLLA: null,
            CAINLLB: null,
            CAILGA: 228.8,
            CAILGB: 1,
            CAILLA: null,
            CAILLB: null,
            IAINLGA: 18.43,
            IAINLGB: 0.652,
            IAINLLA: null,
            IAINLLB: null,
            IAILGA: 636.5,
            IAILGB: 0.621,
            IAILLA: null,
            IAILLB: null,
        }
    },
    {
        id: "damage010",
        fluid: "H2S",
        data: {
            CAINLGA: 10.65,
            CAINLGB: 1,
            CAINLLA: null,
            CAINLLB: null,
            CAILGA: 73.25,
            CAILGB: 0.94,
            CAILLA: null,
            CAILLB: null,
            IAINLGA: 41.43,
            IAINLGB: 0.63,
            IAINLLA: null,
            IAINLLB: null,
            IAILGA: 191.5,
            IAILGB: 0.63,
            IAILLA: null,
            IAILLB: null,
        }
    },
    {
        id: "damage011",
        fluid: "HF",
        data: {
            CAINLGA: null,
            CAINLGB: null,
            CAINLLA: null,
            CAINLLB: null,
            CAILGA: null,
            CAILGB: null,
            CAILLA: null,
            CAILLB: null,
            IAINLGA: null,
            IAINLGB: null,
            IAINLLA: null,
            IAINLLB: null,
            IAILGA: null,
            IAILGB: null,
            IAILLA: null,
            IAILLB: null,
        }
    },
    {
        id: "damage012",
        fluid: "Aromatics",
        data: {
            CAINLGA: 12.76,
            CAINLGB: 0.963,
            CAINLLA: 66.01,
            CAINLLB: 0.883,
            CAILGA: 261.9,
            CAILGB: 0.937,
            CAILLA: 56,
            CAILLB: 0.268,
            IAINLGA: 2.889,
            IAINLGB: 0.686,
            IAINLLA: 0.027,
            IAINLLB: 0.935,
            IAILGA: 83.86,
            IAILGB: 0.713,
            IAILLA: 0.273,
            IAILLB: 0.935,
        }
    },
    {
        id: "damage013",
        fluid: "Styrene",
        data: {
            CAINLGA: 12.76,
            CAINLGB: 0.963,
            CAINLLA: 66.01,
            CAINLLB: 0.883,
            CAILGA: 261.9,
            CAILGB: 0.937,
            CAILLA: 56,
            CAILLB: 0.268,
            IAINLGA: 2.889,
            IAINLGB: 0.686,
            IAINLLA: 0.027,
            IAINLLB: 0.935,
            IAILGA: 83.86,
            IAILGB: 0.713,
            IAILLA: 0.273,
            IAILLB: 0.935,
        }
    },
    {
        id: "damage014",
        fluid: "CO",
        data: {
            CAINLGA: 5.491,
            CAINLGB: 0.991,
            CAINLLA: null,
            CAINLLB: null,
            CAILGA: null,
            CAILGB: null,
            CAILLA: null,
            CAILLB: null,
            IAINLGA: 16.91,
            IAINLGB: 0.692,
            IAINLLA: null,
            IAINLLB: null,
            IAILGA: null,
            IAILGB: null,
            IAILLA: null,
            IAILLB: null,
        }
    },
    {
        id: "damage015",
        fluid: "DEE",
        data: {
            CAINLGA: 26.76,
            CAINLGB: 1.025,
            CAINLLA: 236.7,
            CAINLLB: 1.219,
            CAILGA: 241.5,
            CAILGB: 0.997,
            CAILLA: 488.9,
            CAILLB: 0.864,
            IAINLGA: 31.71,
            IAINLGB: 0.682,
            IAINLLA: 8.33,
            IAINLLB: 0.814,
            IAILGA: 128.3,
            IAILGB: 0.657,
            IAILLA: 9.258,
            IAILLB: 0.814,
        }
    },
    {
        id: "damage016",
        fluid: "Methanol",
        data: {
            CAINLGA: 0,
            CAINLGB: 1.008,
            CAINLLA: 849.9,
            CAINLLB: 0.902,
            CAILGA: null,
            CAILGB: null,
            CAILLA: null,
            CAILLB: null,
            IAINLGA: 6.035,
            IAINLGB: 0.688,
            IAINLLA: 1.157,
            IAINLLB: 0.871,
            IAILGA: null,
            IAILGB: null,
            IAILLA: null,
            IAILLB: null,
        }
    },
    {
        id: "damage017",
        fluid: "EO",
        data: {
            CAINLGA: 11,
            CAINLGB: 1.105,
            CAINLLA: null,
            CAINLLB: null,
            CAILGA: null,
            CAILGB: null,
            CAILLA: null,
            CAILLB: null,
            IAINLGA: 3.47,
            IAINLGB: 0.665,
            IAINLLA: null,
            IAINLLB: null,
            IAILGA: null,
            IAILGB: null,
            IAILLA: null,
            IAILLB: null,
        }
    },
    {
        id: "damage018",
        fluid: "Pyroporic",
        data: {
            CAINLGA: 5.755,
            CAINLGB: 0.96,
            CAINLLA: 70.03,
            CAINLLB: 0.89,
            CAILGA: 188.6,
            CAILGB: 0.92,
            CAILLA: 269.4,
            CAILLB: 0.32,
            IAINLGA: 2.035,
            IAINLGB: 0.66,
            IAINLLA: 1.609,
            IAINLLB: 0.76,
            IAILGA: 151,
            IAILGB: 0.63,
            IAILLA: 2.847,
            IAILLB: 0.54,
        }
    }
]

export { damage, flamable }